# Autogenerated wrapper script for Sol2_jll for any
export sol_hpp

JLLWrappers.@generate_wrapper_header("Sol2")
JLLWrappers.@declare_file_product(sol_hpp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        sol_hpp,
        "include/sol/sol.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
